config/routes.rb
Rails.application.routes.draw do
  # rutas de la aplicacion

   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users 
  resources :clientes
  # get 'home/index'
  root 'home#index'
  get 'home/about'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord

	VALIDA_FORMATO_CORREO = /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i
	VALIDA_FORMATO_NOMBRE =   /\A[a-zA-Z]+\z/
	VALIDA_FORMATO_APELLIDO =   /\A[a-zA-Z]+\z/
	VALIDA_FORMATO_TIPO_PERSONA =   /\A[a-zA-Z]+\z/
	

	belongs_to :user  # creamos las relaciones entre tablas

	# agregamos las validaciones necesarias a nivel de la app
	validates :tipo_persona, format: { with: VALIDA_FORMATO_TIPO_PERSONA }, presence: true
	validates :nro_doc_id, length: {minimun: 8, maximum: 10, message: "Sólo se permiten Números"}, numericality: true, presence: true
	validates :fecha_emision, presence: true 
	validates :fecha_vencimiento, presence: true
	validates :nombre, length: {minimun: 3, maximum: 50}, format: { with: VALIDA_FORMATO_NOMBRE, message: "Sólo se permiten Letras" }, presence: true
	validates :apellido, length: {minimun: 3, maximum: 50}, format: { with: VALIDA_FORMATO_APELLIDO, message: "Sólo se permiten Letras" }, presence: true
	validates :correo, format: { with: VALIDA_FORMATO_CORREO }, uniqueness: true, presence: true
	validates :telf_ppal, length: {minimun: 7, maximum: 15, message: "Sólo se permiten Números" }, numericality: true, presence: true
	validates :telf_sec, length: {minimun: 7, maximum: 15, message: "Sólo se permiten Números"}, numericality: true, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :clientes # creamos las relaciones entre tablas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente Creado Exitosamente." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente Actualizado Exitosamente." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente Eliminado Exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:tipo_persona, :nro_doc_id, :fecha_emision, :fecha_vencimiento, :nombre, 
        :apellido, :correo, :telf_ppal, :telf_sec, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clientes/_cliente.html.erb
<div class="container">
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Tipo Persona:</strong>
    <%= cliente.tipo_persona %>
  </p>

  <p>
    <strong>Número de Documento:</strong>
    <%= cliente.nro_doc_id %>
  </p>

  <p>
    <strong>Fecha Emisión:</strong>
    <%= cliente.fecha_emision %>
  </p>

  <p>
    <strong>Fecha Vencimiento:</strong>
    <%= cliente.fecha_vencimiento %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= cliente.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= cliente.apellido %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= cliente.correo %>
  </p>

  <p>
    <strong>Teléfono Principal:</strong>
    <%= cliente.telf_ppal %>
  </p>

  <p>
    <strong>Teléfono Secundario:</strong>
    <%= cliente.telf_sec %>
  </p>

</div>
</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>

      <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--mostramos el formulario-->

  <div class="container-fluid">
    <%= form.label :tipo_persona, style: "display: block" %>
    <%= form.text_field :tipo_persona, class:"form-control", placeholder:"Tipo de Persona", required:"required" %>
 
    <%= form.label :nro_doc_id, style: "display: block" %>
    <%= form.text_field :nro_doc_id, class:"form-control", placeholder:"Agregar Nro Identificación", required:"required" %>

    <%= form.label :fecha_emision, style: "display: block" %>
    <%= form.date_field :fecha_emision, class:"form-control" %>   
 
    <%= form.label :fecha_vencimiento, style: "display: block" %>
    <%= form.date_field :fecha_vencimiento, class:"form-control" %>

    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre, class:"form-control", placeholder:"Agregar Nombre", required:"required" %>
 
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido, class:"form-control", placeholder:"Agregar Apellido", required:"required" %>

    <%= form.label :correo, style: "display: block" %>
    <%= form.text_field :correo, class:"form-control", placeholder:"Agregar Correo", type:"email", required:"required" %>
  
    <%= form.label :telf_ppal, style: "display: block" %>
    <%= form.text_field :telf_ppal, class:"form-control", placeholder:"Agregar Teléfono", required:"required" %>
 
    <%= form.label :telf_sec, style: "display: block" %>
    <%= form.text_field :telf_sec, class:"form-control", placeholder:"Agregar Teléfono", required:"required" %>

    <%=  %>
    <%= form.number_field :user_id, id: :clientes_user_id, class:"form-control", value: current_user.id, type: :hidden  %>
  </div>

  <br>

  <div>
    <button class="btn btn-success">
    <%= form.submit %>
    </button>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<br>
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Editar Cliente</h1>
      <%= render "form", cliente: @cliente %><br>
      <%= link_to "Mostrar", @cliente, class:"btn btn-info" %> |
      <%= link_to "Volver", clientes_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <h1>Listar Clientes</h1>
  </div>
  <div class="card-body">
    <div id="clientes" class="field form-group">
      <% @clientes.each do |cliente| %>
         <%= render cliente %>        
        <p>
         <%= link_to "Mostrar", cliente, class:"btn btn-success" %> | 
         <%= link_to "Agregar", new_cliente_path, class:"btn btn-info" %>
        </p>
         <% end %>   
    </div>        
  </div>
</div>

app/views/clientes/new.html.erb
<br>
<div class="card">
  <div class="card-header">
    <h5>Nuevo Cliente</h5>
  </div>
  <div class="card-body">
    <div class="field form-group">
      <%= render "form", cliente: @cliente %>
      <%= link_to "Volver", clientes_path, class:"btn btn-info" %>
    </div>
  </div>
</div>

app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

  <%= render @cliente %>

<div class="container">
  <%= link_to "Editar", edit_cliente_path(@cliente), class:"btn btn-info" %> 
  <%= link_to "Volver", clientes_path, class:"btn btn-dark" %>
  <%= button_to "Eliminar", @cliente, method: :delete, class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Siscobank', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Listar Clientes', clientes_path, class:"nav-link" %>       
      </li> 
      <li class="nav-item">
        <%= link_to 'Agregar', new_cliente_path, class:"nav-link" %>       
      </li> 
      <li class="nav-item">
        <%= link_to 'Nosotros', home_about_path, class:"nav-link" %>       
      </li>
      <% if user_signed_in? %>        
        <li class="nav-item">
          <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to 'Editar Perfil', edit_user_registration_path, class:"nav-link" %>       
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Registrarse',  new_user_registration_path, class:"nav-link" %>       
        </li>
        <li class="nav-item">
          <%= link_to 'Ingresar', new_user_session_path, class:"nav-link" %>       
        </li>
      <% end %> 
    </ul>  
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

<p>
	Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere cumque incidunt excepturi dolor dolorum possimus nam suscipit voluptatibus explicabo odit, expedita vel nostrum obcaecati mollitia tempora maxime veniam quibusdam, optio.
</p>

<p>
	Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere cumque incidunt excepturi dolor dolorum possimus nam suscipit voluptatibus explicabo odit, expedita vel nostrum obcaecati mollitia tempora maxime veniam quibusdam, optio.
</p>

<p>
	Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere cumque incidunt excepturi dolor dolorum possimus nam suscipit voluptatibus explicabo odit, expedita vel nostrum obcaecati mollitia tempora maxime veniam quibusdam, optio.
</p>

<p>
	Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere cumque incidunt excepturi dolor dolorum possimus nam suscipit voluptatibus explicabo odit, expedita vel nostrum obcaecati mollitia tempora maxime veniam quibusdam, optio.
</p>

app/views/home/index.html.erb
<br><br><br><br><br><br>
<div class="container-fluid">
	<div class="jumbotron jumbotron-fluid">
	  <h1 class="display-4" align="center">Siscotel</h1>
	  <p class="lead"></p>
	  <hr class="my-4"> 
	</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
     <title>Siscotel</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
   
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>

  </head>

  <body>

    <!---open section add the partial file header to use navbar--->
     <!---i used the render method to include the file _header --->
    <%= render 'home/header' %>
    <!---close section add the partial file header to use navbar--->
    
    <div class="container">
        <%= yield %>
    </div>
    
    
    
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>   
  </body>
</html>